name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      # Step 3: Run tests
      - name: Run tests
        run: |
          echo "Running tests for linux-amd64"
          GOOS=linux GOARCH=amd64 go test ./... -v

      # Step 4: Compile binary to check for build issues
      - name: Compile binary
        run: |
          echo "Compiling binary for linux-amd64"
          mkdir -p bin
          GOOS=linux GOARCH=amd64 make

      # Step 5: Verify build output
      - name: List compiled binaries
        run: ls -l ./bin